-- =========================================================================
-- MIGRATION V3: ADD PRIORITY TABLES FOR EXTENDED FEATURE SETS
-- =========================================================================

-- 1. Create AI Search Logs table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'T_AI_SEARCH_LOGS')
BEGIN
    CREATE TABLE T_AI_SEARCH_LOGS (
        F_LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
        F_SEARCH_QUERY NVARCHAR(500) NOT NULL,
        F_USER_SESSION NVARCHAR(256) NOT NULL,
        F_RESPONSE_TIME_MS INT NOT NULL,
        F_MODEL_USED NVARCHAR(100) NOT NULL,
        F_TIMESTAMP DATETIME DEFAULT GETDATE(),
        F_RESULT_COUNT INT NOT NULL
    );
    PRINT 'Created T_AI_SEARCH_LOGS table.';
END
ELSE
BEGIN
    PRINT 'T_AI_SEARCH_LOGS table already exists.';
END

-- 2. Create User Bookmarks table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'T_USER_BOOKMARKS')
BEGIN
    CREATE TABLE T_USER_BOOKMARKS (
        F_BOOKMARK_ID INT IDENTITY(1,1) PRIMARY KEY,
        F_USER_SESSION NVARCHAR(256) NOT NULL,
        F_PRODUCT_ID INT NOT NULL,
        F_CREATED_AT DATETIME DEFAULT GETDATE(),
        CONSTRAINT FK_T_USER_BOOKMARKS_T_PRODUCTS FOREIGN KEY (F_PRODUCT_ID) REFERENCES T_PRODUCTS(F_PRODUCT_ID) ON DELETE CASCADE
    );
    PRINT 'Created T_USER_BOOKMARKS table.';
END
ELSE
BEGIN
    PRINT 'T_USER_BOOKMARKS table already exists.';
END

-- 3. Create Product Comparisons table
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'T_PRODUCT_COMPARISONS')
BEGIN
    CREATE TABLE T_PRODUCT_COMPARISONS (
        F_COMPARISON_ID INT IDENTITY(1,1) PRIMARY KEY,
        F_USER_SESSION NVARCHAR(256) NOT NULL,
        F_PRODUCT_IDS NVARCHAR(256) NOT NULL,
        F_CREATED_AT DATETIME DEFAULT GETDATE()
    );
    PRINT 'Created T_PRODUCT_COMPARISONS table.';
END
ELSE
BEGIN
    PRINT 'T_PRODUCT_COMPARISONS table already exists.';
END
GO
